# -*- coding: utf-8 -*-
"""Data preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eWU5ujEOx6mouQo7u6D60KaT4b3l2jpJ

**READING ZIP CODES BY POPULATION**
"""

import pandas as pd

df = pd.read_html('https://www.washington-demographics.com/zip_codes_by_population',header=0)
population_df = df[0]
population_df.head()

"""**COLLECTING POVERTY STATUS DATA FOR AREA ZIP CODE**"""

#Read 98007 poverty_status.csv
from google.colab import files
uploaded = files.upload()

import io
povertystatus_df = pd.read_csv(io.BytesIO(uploaded['98007 poverty_status.csv']))
povertystatus_df.head()

#Read 98290 poverty_status
from google.colab import files
uploaded = files.upload()

f98290_ps_df = pd.read_csv(io.BytesIO(uploaded['98290 poverty_status.csv']))
f98290_ps_df.head()

#Read 98065 poverty status.csv
from google.colab import files
uploaded = files.upload()

f98065_ps_df = pd.read_csv(io.BytesIO(uploaded['98065 poverty status.csv']))
f98065_ps_df.head()

#Read 98801 poverty status.csv
from google.colab import files
uploaded = files.upload()

f98801_ps_df = pd.read_csv(io.BytesIO(uploaded['98801 poverty status.csv']))
f98801_ps_df.head()

#Read 98104 poverty status.csv
from google.colab import files
uploaded = files.upload()

f98104_ps_df = pd.read_csv(io.BytesIO(uploaded['98104 poverty status.csv']))
f98104_ps_df.head()

population_df.shape
population_df.ndim

"""**COLLECTING AREA AGE DATA BY POPULATION**"""

#Read 98007 Age_data.csv
from google.colab import files
uploaded = files.upload()

f98007_age_df = pd.read_csv(io.BytesIO(uploaded['98007 Age_data.csv']))
f98007_age_df.head()

#Read 98290 Age_data.csv
from google.colab import files
uploaded = files.upload()

f98290_age_df = pd.read_csv(io.BytesIO(uploaded['98290 Age_data.csv']))
f98290_age_df.head()

#Read 98065 age_data.csv
from google.colab import files
uploaded = files.upload()

f98065_age_df = pd.read_csv(io.BytesIO(uploaded['98065 age_data.csv']))
f98065_age_df.head()

#Read 98801 Age data.csv
from google.colab import files
uploaded = files.upload()

f98801_age_df = pd.read_csv(io.BytesIO(uploaded['98801 Age data.csv']))
f98801_age_df.head()

#Read 98104 Age data.csv
from google.colab import files
uploaded = files.upload()

f98104_age_df = pd.read_csv(io.BytesIO(uploaded['98104 Age data.csv']))
f98104_age_df.head()

# check the datatypes of dataframe's columns
population_df.dtypes

# check dataframe columns
population_df.columns

# check dataframes statistical summery
population_df.describe()

# check 1st 5 rows of dataframe
population_df.head()

"""**DATA CLEANING**"""

population_df.tail()

# Now we delete last row which is just the description of the table
population_df = population_df.drop([563], axis=0)

population_df.tail()

# type conversion
population_df = population_df.astype({"Population": int})

population_df['Population'].dtypes

population_df.drop(["Rank"], axis = 1, inplace = True)

population_df.head()

"""**DATA MANIPULATION**"""

#extract required information for area zip codes
df1 = population_df[population_df['Zip Code'].isin(['98007','98290','98065','98801','98104']) ]
df1

# reset index 
df1 = df1.reset_index(drop=True)
df1

# make dataframe according to document
facility_id = ['A','B','C','D','E']
facility_area_zip_code = ['98007','98290','98065','98801','98104'] 
facility_staff_count = [21, 52, 43, 9, 64]
df2 = pd.DataFrame({'Facility ID': facility_id,
                         'Zip Code': facility_area_zip_code,
                          'Facility Staff Count': facility_staff_count
                        })
df2

# merge both dataframes df1 & df2 
facilities = pd.merge(df2, df1, on = 'Zip Code')
facilities

# order dataframe
facilities = facilities[['Facility ID', 'Zip Code', 'Population', 'Facility Staff Count']]
facilities

facilities = facilities.rename(columns={'Zip Code': 'Zip_Code'})
facilities

#extracting poverty data for areas
f98007_poverty_rate=povertystatus_df['S1701_C03_001E']
f98007_poverty_rate[1]
f98290_poverty_rate=f98290_ps_df['S1701_C03_001E']
f98290_poverty_rate[1]
f98065_poverty_rate=f98065_ps_df['S1701_C03_001E']
f98065_poverty_rate[1]
f98801_poverty_rate=f98801_ps_df['S1701_C03_001E']
f98801_poverty_rate[1]
f98104_poverty_rate=f98104_ps_df['S1701_C03_001E']
f98104_poverty_rate[1]

#creating poverty rate column
facilities['Poverty rate']=""
facilities.loc[facilities.Zip_Code == '98007','Poverty rate']=f98007_poverty_rate[1]
facilities.loc[facilities.Zip_Code == '98290','Poverty rate']=f98290_poverty_rate[1]
facilities.loc[facilities.Zip_Code == '98065','Poverty rate']=f98065_poverty_rate[1]
facilities.loc[facilities.Zip_Code == '98801','Poverty rate']=f98801_poverty_rate[1]
facilities.loc[facilities.Zip_Code == '98104','Poverty rate']=f98104_poverty_rate[1]
facilities

#extracting age data for areas

f98007_under5=f98007_age_df['S0101_C02_002E']
f98007_under5[1]

f98007_70to74=f98007_age_df['S0101_C02_016E']
f98007_70to74[1]

f98007_75to79=f98007_age_df['S0101_C02_017E']
f98007_75to79[1]  

f98007_80to84=f98007_age_df['S0101_C02_018E']
f98007_80to84[1]

f98007_above85=f98007_age_df['S0101_C02_019E']
f98007_above85[1]

f98290_under5=f98290_age_df['S0101_C02_002E']
f98290_under5[1]

f98290_70to74=f98290_age_df['S0101_C02_016E']
f98290_70to74[1]

f98290_75to79=f98290_age_df['S0101_C02_017E']
f98290_75to79[1]  

f98290_80to84=f98290_age_df['S0101_C02_018E']
f98290_80to84[1]

f98290_above85=f98290_age_df['S0101_C02_019E']
f98290_above85[1]

f98065_under5=f98065_age_df['S0101_C02_002E']
f98065_under5[1]

f98065_70to74=f98065_age_df['S0101_C02_016E']
f98065_70to74[1]

f98065_75to79=f98065_age_df['S0101_C02_017E']
f98065_75to79[1]  

f98065_80to84=f98065_age_df['S0101_C02_018E']
f98065_80to84[1]

f98065_above85=f98065_age_df['S0101_C02_019E']
f98065_above85[1]

f98801_under5=f98801_age_df['S0101_C02_002E']
f98801_under5[1]

f98801_70to74=f98801_age_df['S0101_C02_016E']
f98801_70to74[1]

f98801_75to79=f98801_age_df['S0101_C02_017E']
f98801_75to79[1]  

f98801_80to84=f98801_age_df['S0101_C02_018E']
f98801_80to84[1]

f98801_above85=f98801_age_df['S0101_C02_019E']
f98801_above85[1]

f98104_under5=f98104_age_df['S0101_C02_002E']
f98801_under5[1]

f98104_70to74=f98104_age_df['S0101_C02_016E']
f98104_70to74[1]

f98104_75to79=f98104_age_df['S0101_C02_017E']
f98104_75to79[1]  

f98104_80to84=f98104_age_df['S0101_C02_018E']
f98104_80to84[1]

f98104_above85=f98104_age_df['S0101_C02_019E']
f98104_above85[1]

#creating age columns
facilities['Age < 5(%)']=""
facilities.loc[facilities.Zip_Code == '98007','Age < 5(%)']=f98007_under5[1]
facilities.loc[facilities.Zip_Code == '98290','Age < 5(%)']=f98290_under5[1]
facilities.loc[facilities.Zip_Code == '98065','Age < 5(%)']=f98065_under5[1]
facilities.loc[facilities.Zip_Code == '98801','Age < 5(%)']=f98801_under5[1]
facilities.loc[facilities.Zip_Code == '98104','Age < 5(%)']=f98104_under5[1]
facilities

facilities['Age 70-74(%)']=""
facilities.loc[facilities.Zip_Code == '98007','Age 70-74(%)']=f98007_70to74[1]
facilities.loc[facilities.Zip_Code == '98290','Age 70-74(%)']=f98290_70to74[1]
facilities.loc[facilities.Zip_Code == '98065','Age 70-74(%)']=f98065_70to74[1]
facilities.loc[facilities.Zip_Code == '98801','Age 70-74(%)']=f98801_70to74[1]
facilities.loc[facilities.Zip_Code == '98104','Age 70-74(%)']=f98104_70to74[1]

facilities

facilities['Age 75-79(%)']=""
facilities.loc[facilities.Zip_Code == '98007','Age 75-79(%)']=f98007_75to79[1]
facilities.loc[facilities.Zip_Code == '98290','Age 75-79(%)']=f98290_75to79[1]
facilities.loc[facilities.Zip_Code == '98065','Age 75-79(%)']=f98065_75to79[1]
facilities.loc[facilities.Zip_Code == '98801','Age 75-79(%)']=f98801_75to79[1]
facilities.loc[facilities.Zip_Code == '98104','Age 75-79(%)']=f98104_75to79[1]
facilities

facilities['Age 80-84(%)']=""
facilities.loc[facilities.Zip_Code == '98007','Age 80-84(%)']=f98007_80to84[1]
facilities.loc[facilities.Zip_Code == '98290','Age 80-84(%)']=f98290_80to84[1]
facilities.loc[facilities.Zip_Code == '98065','Age 80-84(%)']=f98065_80to84[1]
facilities.loc[facilities.Zip_Code == '98801','Age 80-84(%)']=f98801_80to84[1]
facilities.loc[facilities.Zip_Code == '98104','Age 80-84(%)']=f98104_80to84[1]
facilities

facilities['Age > 85(%)']=""
facilities.loc[facilities.Zip_Code == '98007','Age > 85(%)']=f98007_above85[1]
facilities.loc[facilities.Zip_Code == '98290','Age > 85(%)']=f98290_above85[1]
facilities.loc[facilities.Zip_Code == '98065','Age > 85(%)']=f98065_above85[1]
facilities.loc[facilities.Zip_Code == '98801','Age > 85(%)']=f98801_above85[1]
facilities.loc[facilities.Zip_Code == '98104','Age > 85(%)']=f98104_above85[1]

facilities

# facilities
facilities = facilities.astype({"Age 70-74(%)": float})
facilities = facilities.astype({"Age 75-79(%)": float})
facilities = facilities.astype({"Age 80-84(%)": float})
facilities = facilities.astype({"Age > 85(%)": float})
facilities = facilities.astype({"Age < 5(%)": float})
facilities = facilities.astype({"Poverty rate": float})
#creating priority populaton which is a sum of all the population that may require more healthcare needs
facilities["priority population(%) "] = facilities["Age 70-74(%)"] + facilities["Age 75-79(%)"]+facilities["Age 80-84(%)"] + facilities["Age > 85(%)"]+ facilities["Age < 5(%)"]
# del facilities['priroity population']

facilities

#drop unnecessary columns
facilities=facilities.drop(['Age < 5(%)', 'Age 70-74(%)','Age 75-79(%)', 'Age 80-84(%)', 'Age > 85(%)'], axis=1)
facilities

facilities.to_csv(r 'Structured_data.csv')